### ISSUE TITLE
Not functioning properly in MacOS (international keyboard)

### ISSUE THREAD

**Issue by Endzel** [binaryfunt/autoclose-html-plus#3] opened 2019-10-09 16:41 UTC
Just installed your package, followed everything and it looks like it does not work as expected. I saw the initial [issue referenced ](https://github.com/mattberkowitz/autoclose-html/issues/215) from where you forked this repository that was unsolved and I think it may be a similar issue.

**Comment by binaryfunt** [comment] 2019-10-10 16:20
Is there a reason you have closed this issue?

**Comment by Endzel** [comment] 2019-10-10 17:39
Because it started to function properly right after I created the issue, but now it seems that the problem is back again.

**Comment by binaryfunt** [comment] 2019-10-11 11:53
What have you tried and what have the results (or lack thereof) been? Try opening the console (ctrl+shift+i) and seeing if there are any errors when you try closing a tag

**Comment by Endzel** [comment] 2019-10-11 12:50
So far there are no errors in the console, nor inside Atom whenever I close any kind of tag. I do not know, what else should I try?

**Comment by binaryfunt** [comment] 2019-10-11 15:43
Are you trying this in html, xml or markdown files?

Can you check the keybindings:

1. Open the command palette (Ctrl+Shift+P)
1. Type "keybind" and click "Settings View: Show Keybindings"
1. In the search box, type ">" and then tell me what comes up

**Comment by alessioviola** [comment] 2019-10-19 15:33
Not working for me too. Installed the package but no tag will close automatically.

**Comment by binaryfunt** [comment] 2019-10-19 17:23
@guyfawkes85 Can you answer the questions I've asked above? Unfortunately without more info I can't get to the bottom of this.

**Comment by lroggen** [comment] 2019-10-20 00:14
I'm assuming this is due to the keybindings not adding a selector for .js files:
`atom-text-editor[data-grammar~="js"]`

**Comment by lroggen** [comment] 2019-10-20 00:47
I opened a PR but that may be an expanded scope for this project. The easiest way to fix this for me was adding the snippet below to the bottom of my keymap.cson (on Mac: Atom > Keymap...)
```
'atom-text-editor[data-grammar~="js"]':
	'>': 'autoclose-html-plus:close-and-complete'
```

**Comment by binaryfunt** [comment] 2019-10-20 14:42
@lroggen That is certainly a possible enhancement, though it appears to be separate from this issue. Creating a new issue for it - #6

**Comment by alessioviola** [comment] 2019-10-26 14:17
Hi @binaryfunt , sorry for my incomplete sentence. I've tried this in html. Following your instructions, I've searched in keybindings option and typing ">" it returns me 3 strings with different selectors for html, xml and gfm:

Keystroke: >
Command: autoclose-html-plus:close-and-complete
Source: Autoclose Html Plus
Selector: atom-text-editor[data-grammar~="html"]

**Comment by Endzel** [comment] 2019-10-28 11:57
Having the same results as @guyfawkes85 here in my command palette. It turns out that my files are using VueComponent and PHP grammar. Even though, I tried with some other files with HTML grammar and it did not work either, neither showing any error on Atom's console.

Anyway, could it be made to trigger in any file, independently of the grammar it uses, and then later on just check if they is an HTML tag opener in the same line?

**Comment by binaryfunt** [comment] 2019-10-28 17:37
Hmm, this is puzzling. Could you try doing this:

1. Open your custom keymap file by typing "keymap" in the command palette and clicking "Application: Open Your Keymap"
1. Paste this in the bottom of the keymap file and save it:
    ```
    'atom-text-editor[data-grammar~="html"]':
      '>': 'application:about'
    ```
1. Open or create a new HTML file, then type `>`

It should open the Atom "about" page.


(After this, delete that pasted text from your keymap)

**Comment by alessioviola** [comment] 2019-11-10 17:00
@binaryfunt probably I've found the issue, even if I still don't know how to fix this. I don't know which is the cause, but writing the | (pipe symbol) in Atom with your package enabled is impossible, cause holding CAPS+BACKSLASH pops out the closing tag symbol >. And (surprise, surprise) the autoclose works! Of course, it is seriously hard, working closing tag with CAPS+BACKSLASH every time, but probably now we are more close to solve the issue definitively even for Mac users. I hope this will help you figure out which can be the problem. Have a nice day :)

**Comment by binaryfunt** [comment] 2019-11-11 17:13
@guyfawkes85 Ah, so this is an issue with how Atom registers keypresses. Do you have a non-QWERTY keyboard layout? Or a non-English layout in some way?

There is [an option for "International mode"](https://github.com/binaryfunt/autoclose-html-plus#legacyinternational-mode) in the package settings, which was made by the original developer of autoclose-html. It may be a little buggy, but it seems to work.

**Comment by Endzel** [comment] 2019-12-10 10:45
@binaryfunt That "legacy mode" option worked for me! Anyway it seems to me that there is still an issue here that needs to be resolved, we should not be using this legacy buggy mode as the very same original author remarked.

Thanks for following the thread and give us a hand here!

**Comment by binaryfunt** [comment] 2019-12-10 12:29
@Endzel Unfortunately because the actual problem is with how Atom registers keypresses, there isn't much you can do other than check every keystroke for if it is <kbd>></kbd> (this is what legacy mode does), which has got to be less performant than using the built-in Atom keybindings. So I'm unwilling to make that the default behaviour. As such, I'm closing this issue.

**Closed as completed** 2019-12-10 12:30 UTC
Labels: question
